name: CI - Build and Run Spring Boot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: appuser
          POSTGRES_PASSWORD: "!appuser123!"
          POSTGRES_DB: northwind
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build the app
        run: mvn clean package -DskipTests

      - name: Run the app and test it starts
        run: |
          java -DSPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/northwind \
          -DSPRING_DATASOURCE_USERNAME=appuser \
          -DSPRING_DATASOURCE_PASSWORD=!appuser123! \
          -jar target/*.jar
          sleep 10
          curl -f http://localhost:8008/api/customers || (echo "App failed to start" && exit 1)
